#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libraw-soname19
Version  : 0.19.5
Release  : 20
URL      : https://www.libraw.org/data/LibRaw-0.19.5.tar.gz
Source0  : https://www.libraw.org/data/LibRaw-0.19.5.tar.gz
Summary  : Raw image decoder library (thread-safe)
Group    : Development/Tools
License  : CDDL-1.1 LGPL-2.1
Requires: compat-libraw-soname19-lib = %{version}-%{release}
Requires: compat-libraw-soname19-license = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(lcms2)

%description
LibRaw can decode most common DNG formats (Bayer/Linear, 16-bit integer and
floating point) by itself (you need to use zlib for deflate decompression
support and libjpeg for lossy compressed DNGs).

%package lib
Summary: lib components for the compat-libraw-soname19 package.
Group: Libraries
Requires: compat-libraw-soname19-license = %{version}-%{release}

%description lib
lib components for the compat-libraw-soname19 package.


%package license
Summary: license components for the compat-libraw-soname19 package.
Group: Default

%description license
license components for the compat-libraw-soname19 package.


%prep
%setup -q -n LibRaw-0.19.5
cd %{_builddir}/LibRaw-0.19.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595526193
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1595526193
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libraw-soname19
cp %{_builddir}/LibRaw-0.19.5/COPYRIGHT %{buildroot}/usr/share/package-licenses/compat-libraw-soname19/aae7ee73fdea4b41593aa2eca7ce3122e6f9d392
cp %{_builddir}/LibRaw-0.19.5/LICENSE.CDDL %{buildroot}/usr/share/package-licenses/compat-libraw-soname19/c24b9c7ef03687bf0141f85a1b7ed81459944c3c
cp %{_builddir}/LibRaw-0.19.5/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/compat-libraw-soname19/39a21f33cadea18adcc23bf808d7d5ea6419c8b1
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/4channels
rm -f %{buildroot}/usr/bin/dcraw_emu
rm -f %{buildroot}/usr/bin/dcraw_half
rm -f %{buildroot}/usr/bin/half_mt
rm -f %{buildroot}/usr/bin/mem_image
rm -f %{buildroot}/usr/bin/multirender_test
rm -f %{buildroot}/usr/bin/postprocessing_benchmark
rm -f %{buildroot}/usr/bin/raw-identify
rm -f %{buildroot}/usr/bin/simple_dcraw
rm -f %{buildroot}/usr/bin/unprocessed_raw
rm -f %{buildroot}/usr/include/libraw/libraw.h
rm -f %{buildroot}/usr/include/libraw/libraw_alloc.h
rm -f %{buildroot}/usr/include/libraw/libraw_const.h
rm -f %{buildroot}/usr/include/libraw/libraw_datastream.h
rm -f %{buildroot}/usr/include/libraw/libraw_internal.h
rm -f %{buildroot}/usr/include/libraw/libraw_types.h
rm -f %{buildroot}/usr/include/libraw/libraw_version.h
rm -f %{buildroot}/usr/lib64/libraw.so
rm -f %{buildroot}/usr/lib64/libraw_r.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libraw.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libraw_r.pc
rm -f %{buildroot}/usr/share/doc/libraw/COPYRIGHT
rm -f %{buildroot}/usr/share/doc/libraw/Changelog.txt
rm -f %{buildroot}/usr/share/doc/libraw/LICENSE.CDDL
rm -f %{buildroot}/usr/share/doc/libraw/LICENSE.LGPL

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libraw.so.19
/usr/lib64/libraw.so.19.0.2
/usr/lib64/libraw_r.so.19
/usr/lib64/libraw_r.so.19.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libraw-soname19/39a21f33cadea18adcc23bf808d7d5ea6419c8b1
/usr/share/package-licenses/compat-libraw-soname19/aae7ee73fdea4b41593aa2eca7ce3122e6f9d392
/usr/share/package-licenses/compat-libraw-soname19/c24b9c7ef03687bf0141f85a1b7ed81459944c3c
